"""new tables

Revision ID: c1944c0b2843
Revises:
Create Date: 2025-02-19 23:30:14.117035

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c1944c0b2843"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orders",
        sa.Column("promo_code", sa.String(length=30), nullable=True),
        sa.Column("total_price", sa.Float(), nullable=False),
        sa.Column("pk", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("pk"),
    )
    op.create_table(
        "products",
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(length=560), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("pk", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("pk"),
    )
    op.create_table(
        "reviews",
        sa.Column("review_text", sa.Text(length=360), nullable=False),
        sa.Column("review_mark", sa.Integer(), nullable=False),
        sa.Column("pk", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("pk"),
    )
    op.create_table(
        "roles",
        sa.Column("name", sa.String(length=40), nullable=False),
        sa.Column("pk", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("pk"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "shop",
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(length=560), nullable=False),
        sa.Column("pk", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("pk"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "products_orders_association",
        sa.Column("products_pk", sa.BigInteger(), nullable=False),
        sa.Column("orders_pk", sa.BigInteger(), nullable=False),
        sa.Column("pk", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["orders_pk"],
            ["orders.pk"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["products_pk"],
            ["products.pk"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("pk"),
        sa.UniqueConstraint(
            "products_pk",
            "orders_pk",
            name="idx_unique_products_orders_relation",
        ),
    )
    op.create_table(
        "reviews_products_association",
        sa.Column("products_pk", sa.BigInteger(), nullable=False),
        sa.Column("reviews_pk", sa.BigInteger(), nullable=False),
        sa.Column("pk", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["products_pk"],
            ["products.pk"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reviews_pk"],
            ["reviews.pk"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("pk"),
        sa.UniqueConstraint(
            "products_pk",
            "reviews_pk",
            name="idx_unique_products_reviews_relation",
        ),
    )
    op.create_table(
        "users",
        sa.Column("phone", sa.String(length=150), nullable=False),
        sa.Column("password", sa.String(length=50), nullable=False),
        sa.Column("first_name", sa.String(length=60), nullable=False),
        sa.Column("last_name", sa.String(length=60), nullable=False),
        sa.Column("role", sa.BigInteger(), nullable=False),
        sa.Column(
            "started_at",
            sa.TIMESTAMP(),
            server_default=sa.text("(TIMEZONE('utc', now()))"),
            nullable=False,
        ),
        sa.Column("pk", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["role"], ["roles.pk"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("pk"),
        sa.UniqueConstraint("phone"),
    )
    op.create_table(
        "reviews_users_association",
        sa.Column("users_pk", sa.BigInteger(), nullable=False),
        sa.Column("reviews_pk", sa.BigInteger(), nullable=False),
        sa.Column("pk", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["reviews_pk"],
            ["reviews.pk"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["users_pk"], ["users.pk"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("pk"),
        sa.UniqueConstraint(
            "users_pk", "reviews_pk", name="idx_unique_users_reviews_relation"
        ),
    )
    op.create_table(
        "users_orders_association",
        sa.Column("user_pk", sa.BigInteger(), nullable=False),
        sa.Column("orders_pk", sa.BigInteger(), nullable=False),
        sa.Column("pk", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["orders_pk"],
            ["orders.pk"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_pk"], ["users.pk"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("pk"),
        sa.UniqueConstraint(
            "user_pk", "orders_pk", name="idx_unique_users_orders_relation"
        ),
    )
    op.create_table(
        "users_shop_association",
        sa.Column("users_pk", sa.BigInteger(), nullable=False),
        sa.Column("shop_pk", sa.BigInteger(), nullable=False),
        sa.Column("pk", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["shop_pk"], ["shop.pk"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["users_pk"], ["users.pk"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("pk"),
        sa.UniqueConstraint(
            "users_pk", "shop_pk", name="idx_unique_users_shop_relation"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users_shop_association")
    op.drop_table("users_orders_association")
    op.drop_table("reviews_users_association")
    op.drop_table("users")
    op.drop_table("reviews_products_association")
    op.drop_table("products_orders_association")
    op.drop_table("shop")
    op.drop_table("roles")
    op.drop_table("reviews")
    op.drop_table("products")
    op.drop_table("orders")
    # ### end Alembic commands ###
